DROP TABLE IF EXISTS comments;
CREATE TABLE comments (
    id SERIAL PRIMARY KEY,
    image_id INTEGER REFERENCES images(id),
    comment VARCHAR(600) NOT NULL,
    username VARCHAR(600) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)
